// <auto-generated />
using System;
using ChequeCtrl_Web.Dados.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ChequeCtrl_Web.Migrations
{
    [DbContext(typeof(ChequeContext))]
    partial class ChequeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("chq")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

            modelBuilder.Entity("ChequeCtrl_Web.Models.Banco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<string>("Codigo")
                        .HasMaxLength(3)
                        .HasColumnType("varchar")
                        .HasColumnName("Codigo");

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Nome");

                    b.HasKey("Id")
                        .HasName("PK_Bancos");

                    b.ToTable("BANCOS");
                });

            modelBuilder.Entity("ChequeCtrl_Web.Models.Cheque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<int?>("BancoId")
                        .HasColumnType("integer")
                        .HasColumnName("Banco");

                    b.Property<DateTime?>("Emissao")
                        .HasColumnType("date")
                        .HasColumnName("Emissao");

                    b.Property<int?>("Folha")
                        .HasColumnType("integer")
                        .HasColumnName("Folha");

                    b.Property<int?>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("Numero");

                    b.Property<int?>("Passou_Para")
                        .HasColumnType("integer")
                        .HasColumnName("Passou_Pra_Quem");

                    b.Property<int?>("PessoaId")
                        .HasColumnType("integer")
                        .HasColumnName("Dono");

                    b.Property<string>("Situacao")
                        .HasColumnType("char(1)")
                        .HasColumnName("Situacao");

                    b.Property<string>("Tipo")
                        .HasColumnType("char(1)")
                        .HasColumnName("Tipo");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("money")
                        .HasColumnName("Valor");

                    b.Property<DateTime?>("Vencimento")
                        .HasColumnType("date")
                        .HasColumnName("Vencimento");

                    b.HasKey("Id")
                        .HasName("PK_Cheques");

                    b.HasIndex("BancoId");

                    b.HasIndex("Passou_Para");

                    b.HasIndex("PessoaId");

                    b.ToTable("CHEQUES");
                });

            modelBuilder.Entity("ChequeCtrl_Web.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<string>("CNPJ")
                        .HasMaxLength(14)
                        .HasColumnType("varchar")
                        .HasColumnName("CNPJ");

                    b.Property<string>("CPF")
                        .HasMaxLength(11)
                        .HasColumnType("varchar")
                        .HasColumnName("CPF");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("Endereco");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("Telefone");

                    b.HasKey("Id")
                        .HasName("PK_Pessoas");

                    b.ToTable("PESSOAS");
                });

            modelBuilder.Entity("ChequeCtrl_Web.Models.Cheque", b =>
                {
                    b.HasOne("ChequeCtrl_Web.Models.Banco", "Bancos")
                        .WithMany("Cheques")
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ChequeCtrl_Web.Models.Pessoa", "PessoaPegou")
                        .WithMany("ChequesRepassados")
                        .HasForeignKey("Passou_Para")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ChequeCtrl_Web.Models.Pessoa", "PessoaDono")
                        .WithMany("Cheques")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Bancos");

                    b.Navigation("PessoaDono");

                    b.Navigation("PessoaPegou");
                });

            modelBuilder.Entity("ChequeCtrl_Web.Models.Banco", b =>
                {
                    b.Navigation("Cheques");
                });

            modelBuilder.Entity("ChequeCtrl_Web.Models.Pessoa", b =>
                {
                    b.Navigation("Cheques");

                    b.Navigation("ChequesRepassados");
                });
#pragma warning restore 612, 618
        }
    }
}
